ubiquity-os-marketplace/text-conversation-rewards

src/index.ts, src/run.ts, tests/__mocks__/handlers.ts, tests/action.test.ts, tests/process.issue.test.ts
Resolves #25 
QA run: https://github.com/Meniole/todel/issues/1#issuecomment-2138784229
=> fix: issue closed as non-planned is now skipped

.github/workflows/jest-testing.yml, .github/workflows/release-please.yml, README.md, src/configuration/incentives.ts, src/helpers/label-price-extractor.ts, src/parser/user-extractor-module.ts, src/run.ts, tests/price-label.test.ts
=> fix: price label is required to run

README.md, src/configuration/formatting-evaluator-config.ts, src/configuration/incentives.ts, src/parser/formatting-evaluator-module.ts, src/run.ts
=> chore: rename variables

.github/workflows/jest-testing.yml, jest.config.ts, package.json, yarn.lock
Resolves https://github.com/ubiquity/ts-template/issues/50
=> chore: added Jest reporter

package.json, src/parser/content-evaluator-module.ts, yarn.lock
Resolves https://github.com/ubiquibot/conversation-rewards/issues/30
- removed `js-tiktoken` due to the 128k token limit and strict `GPT-4o` usage
- making one call instead of a batch of 10
=> GPT-4o usage

CHANGELOG.md, manifest.json, yarn.lock
Relates to https://github.com/ubiquity/ubiquibot-kernel/pull/71
=> Manifest file

src/parser/github-comment-module.ts
QA: https://github.com/Meniole/conversation-rewards/issues/10#issuecomment-2346237233
=> feat: strip long content

src/helpers/constants.ts, src/parser/github-comment-module.ts, src/run.ts, tests/truncate-data.test.ts, yarn.lock
Fixes https://github.com/ubiquity-os/ubiquity-os-kernel/issues/80#issuecomment-2395411313
=> fix: large payload

src/parser/content-evaluator-module.ts
Reverts ubiquity-os-marketplace/text-conversation-rewards#151
=> Revert "(refactor) improve comment prompt"

CHANGELOG.md, src/parser/content-evaluator-module.ts, src/parser/formatting-evaluator-module.ts, src/parser/github-comment-module.ts, tests/fees.test.ts
Resolves #113
QA: https://github.com/Meniole/conversation-rewards/issues/26#issuecomment-2451244728
=> fix: zero-display

src/parser/formatting-evaluator-module.ts
=> Merge development into main

manifest.json
Resolves https://github.com/ubiquity-os/ubiquity-os-kernel/issues/232
=> fix: added skipBotEvents to manifest.json

src/web/api/index.ts, src/web/api/payload.ts
Resolves #247 
- Fix CORS
- Change payload to the new unified format
=> Fix payload and CORS

src/parser/formatting-evaluator-module.ts, src/parser/github-comment-module.ts, tests/parser/formatting-evaluator-module.test.ts
=> fix: formatting score decimals

bun.lock, src/issue-activity.ts, src/parser/content-evaluator-module.ts, src/parser/data-purge-module.ts, src/parser/formatting-evaluator-module.ts, src/parser/github-comment-module.ts, src/types/results.ts, tests/parser/permit-generation-module.test.ts, tests/process.issue.test.ts
Fixes a collision with a GitHub type and our own types.
=> fix: rename type to commentType

bun.lock, src/parser/github-comment-module.ts, src/parser/processor.ts, src/run.ts, tests/price-label.test.ts, tests/process.issue.test.ts
=> fix: cap rewards to zero when price tag is explicitly set to zero

README.md
Added some docs on how to set up permit fees, which was not documented.
=> docs: added doc for permit fees

src/helpers/web3.ts, src/parser/github-comment-module.ts, tests/fees.test.ts, tests/helpers/web3-mocks.ts, tests/parser/payment-module.test.ts, tests/payment-generatable.test.ts, tests/process.issue.test.ts, tests/rewards.test.ts
Resolves #302 
QA: https://github.com/ubiquibot-whilefoo-testing/testing/issues/60
=> Skip claimed reward

README.md, manifest.json, package.json, src/parser/github-comment-module.ts, src/parser/payment-module.ts, src/parser/simplification-incentivizer-module.ts, src/types/plugin-input.ts, tests/__mocks__/results/valid-configuration.json
Hotfixes related to comments on #326
=> chore: hotfix for #326

README.md, manifest.json, src/configuration/content-evaluator-config.ts, src/helpers/original-author.ts, src/parser/content-evaluator-module.ts, src/parser/github-comment-module.ts, src/types/results.ts, tests/__mocks__/handlers.ts, tests/__mocks__/results/content-evaluator-test-result.json, tests/__mocks__/results/valid-configuration.json, tests/__mocks__/routes/issue-71-comments-get.json, tests/__mocks__/routes/issue-71-events-get.json, tests/__mocks__/routes/issue-71-get.json, tests/__mocks__/routes/issue-71-timeline-get.json, tests/content-evaluator-config.test.ts, tests/specification.test.ts
=> fix: add reward mechanism for original comment authors

.github/workflows/compute.yml
Resolves https://github.com/ubiquity-os/ubiquity-os-kernel/issues/281
=> fix: set environment main for main branch and tags

src/parser/github-comment-module.ts, tests/fees.test.ts
=> fix: no more commas are displayed for the rows, conversation hidden if empty

.github/workflows/release-please.yml
Add issues: write under permissions for release-please workflow.
=> fix: release please issue permission

src/helpers/diff-count.ts, src/parser/content-evaluator-module.ts, src/parser/data-purge-module.ts, src/web/.ubiquity-os.config.yml, tests/helpers/diff-count.test.ts
=> HTML comments are not taken into account for authorship

bun.lock, package.json, src/web/.ubiquity-os.config.yml, src/web/api/index.ts, src/web/api/payload.ts
Resolves https://github.com/ubiquity-os/plugin-sdk/issues/107
=> SDK version bump
